apiVersion: core.rukpak.io/v1alpha1
kind: BundleDeployment
metadata:
  name: helm-proto1
spec:
  provisionerClassName: core.rukpak.io/plain
  #config:
  #  valuesFrom:
  #    configMapName: apachevalues
  template:
    metadata: {}
    spec:
      provisionerClassName: core.rukpak.io/plain
      source:
        http:
          url: https://charts.bitnami.com/bitnami/apache-9.1.13.tgz  
        type: http
