apiVersion: v1
kind: Service
metadata:
  namespace: rukpak-system
  name: kustomize-provisioner
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: kustomize-provisioner
